### ISSUE TITLE
Calculation is wrong! 

### ISSUE THREAD

**Issue by tirth-hihoriya** [phiresky/levenshtein-demo#1]
In `Levenshtein Distance`, for substituion we take `2` as weight and `1` for insertion and deletion.
But in this code for all three operation `1` weight is taken.

**Comment by phiresky** [comment]
According to Wikipedia: "In Levenshtein's original definition, each of these operations has unit cost (except that substitution of a character by itself has zero cost), so the Levenshtein distance is equal to the minimum number of operations required to transform a to b." https://en.wikipedia.org/wiki/Edit_distance. I can't read the original paper, but I don't think there's specific weights of 2/1/1 prescribed anywhere, at most you can define arbitrary weights for each operation. So it might make sense to have a setting for the weight of each operation, but for this simple demonstration I think it would only make it harder to understand.
